"""users table

Revision ID: 6debf5769824
Revises: f6f30eca7258
Create Date: 2020-02-27 16:00:12.664425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6debf5769824'
down_revision = 'f6f30eca7258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capability', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('need', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('need', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.alter_column('capability', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###
